name: Lint & build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
    - name: Lint & isort
      run: |
        make check
    - name: Build package
      run: |
        make build
    - name: Save built package
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: |
          dist
