name: Lint & build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
    - name: Lint & isort
      run: |
        make check
    - name: Build package
      run: |
        make build
    - name: Save built package
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: |
          dist
